import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { Suspense } from "react";
import AuthProvider from "./auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Mosh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <AuthProvider>
          <Navbar />
          <main className="p-4">
            <Suspense fallback={<span className="loading loading-dots loading-lg text-center"></span>}>

              {children}
            </Suspense>

          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
